# Generated by Django 2.0 on 2018-11-22 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FunctionApi', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='highlighted',
        ),
        migrations.RemoveField(
            model_name='product',
            name='owner',
        ),
    ]
