# Generated by Django 2.1.3 on 2018-11-18 15:25

import ForignRelationShip.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ForignRelationShip', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='company',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ForignRelationShip.Employee', verbose_name=ForignRelationShip.models.Employee),
        ),
        migrations.CreateModel(
            name='MyPerson',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
            },
            bases=('ForignRelationShip.person',),
        ),
    ]
